### ISSUE TITLE
What are good website prototyping tools?

### ISSUE THREAD

**Issue by m2creger** [den-materials/wdi-orientation#11]
google result 1
http://www.creativebloq.com/web-design/top-10-prototyping-tools-2016-21619216

google result 2
https://blog.prototypr.io/the-7-best-prototyping-tools-for-ui-and-ux-designers-in-2016-701263ae65e8

I spoke with David and he did not know.

Marshall

**Comment by nickandersonr** [comment]
Hey Marshall,

Good question! The answer depends highly on the level of fidelity you'd like to achieve:

Low Fidelity:
A whiteboard or cocktail napkin will work. When your only aim is to illustrate your layout with "boxes", really any tool can work.

Medium Fidelity: 
Balsamiq and Mockingbird are good web-based tools for laying out simple designs, with annotations and notes. They allow you to draw basic shapes, and feature some basic components that are common to standard sites. They won't allow much in the way of style or artistic direction, though.

High Fidelity:
Currently the industry standard for full-fledged designs is either Sketch or Photoshop. They both have pros and cons which we'll cover later, but both can be used to produce full, production-quality artwork. Getting work as a designer will require you to know one or both of these.

Does that answer your question?

**Comment by m2creger** [comment]
Thanks Nick!

Much appreciated.
