### ISSUE TITLE
Front-end to full-stack

### ISSUE THREAD

**Issue by MarkKleinfelder** [den-materials/wdi-orientation#12]
What backend programing tools and languages work best, or are most commonly used, with the programming languages we will learn in the WDI course? 

http://blog.udacity.com/2014/12/front-end-vs-back-end-vs-full-stack-web-developers.html

https://medium.com/coderbyte/a-guide-to-becoming-a-full-stack-developer-in-2017-5c3c08a1600c

**Comment by ZebGirouard** [comment]
The best part about dividing web development into "front end" and "back end" is you can mix and match basically anything you want.  That being said, there will be job reqs that will require less self-study to meet.  For instance:

1) Front end developer--you will learn all the skills you *need* for the front end in the next two weeks, and most of the skills you *want* by the end of the course
2) MEAN stack developer--we will teach Mongo, Express, Angular, and Node very deeply in this course
3) Angular developer--this is our framework of choice in Denver
4) Node and/or Express developer--some job postings are just for back end, and these are our main tools for back end dev

Then there are some jobs that might be a bit of a stretch, but an easy stretch:

1) Back-end SQL developer (for website)--people can go VERY deep into SQL, and we spend a week on it
2) PHP developer--we only have a few days on this, but it sets a good foundation
3) Wordpress developer--same as #2, but many people use the phrase "Wordpress developer" to mean "make posts for my blog", make sure it's actually a dev job
4) React developer--we spend less time on this than Angular
5) Any hybrid of the things above

And I'm probably forgetting a few other ones.

Does that answer your question?

**Comment by MarkKleinfelder** [comment]
Question answered! Thanks!
