### ISSUE TITLE
Which JavaScript framework is the best to have experience in? 

### ISSUE THREAD

**Issue by jayverts** [den-materials/wdi-orientation#14]
While looking for a job after class, which JavaScript framework would allow me to land a job the fastest? 

https://www.quora.com/Which-is-the-best-Javascript-Framework-for-beginners

https://www.dunebook.com/5-best-javascript-frameworks-to-learn-in-2017/

**Comment by ZebGirouard** [comment]
Excellent question, Jeremy!  The volume of Angular jobs vs React jobs is much higher, about an order of magnitude higher:

https://www.indeed.com/jobtrends/q-Angularjs-q--React.js.html

That being said, the number of people who can fill those positions is also much higher.  I would look at [Built in Colorado](http://www.builtincolorado.com/), and find whichever has the most job listings that look appealing.  Then throw yourself headlong into it to get one of those jobs.  After you feel comfortable in that one framework, then you might want to explore other ones, again letting open-source projects and jobs that look interesting be your guide (what framework are they using?  I should learn that).

Did that answer your question?

**Comment by jayverts** [comment]
Yes it did! Thanks for all the info Zeb!
