### ISSUE TITLE
Best languages for learn for cyber security

### ISSUE THREAD

**Issue by Astroknut** [den-materials/wdi-orientation#8]
I'm looking for the best languages/backend technologies that I should know when jumping into cyber security. Is there any one technology or language that would benefit me most? Should I focus more on frameworks or languages to ensure secure apps? Is penetration testing the best way to become familiar in this field?

https://www.reddit.com/r/AskComputerScience/comments/3b7ua5/whats_the_best_language_to_learn_for_cyber/

https://news.ycombinator.com/item?id=9754136

I haven't spoken with anyone yet, but it's 4p and homework time!

**Comment by ZebGirouard** [comment]
Hmmm...I don't know about languages, but these are some tools that will be *super* helpful in a web context:

HTTP
SSL/TLS
bcrypt
Password hashing
SSH
RSA
SHA
Hardware and software firewalls

That will get your feet wet.

Once you've got a good grasp on those, I may have to pass you off to a security expert.

Did that answer your question for now, though?

**Comment by Astroknut** [comment]
Absolutely! Appreciate the feedback!
